item {
  id: 1
  name: 'carrefour_market'
}

item {
  id: 2
  name: 'intermarche'
}

item {
  id: 3
  name: 'castorama'
}

item {
  id: 4
  name: 'boulanger'
}

item {
  id: 5
  name: 'dominos'
}

item {
  id: 6
  name: 'ugc'
}

item {
  id: 7
  name: 'carrefour_hyper'
}

item {
  id: 8
  name: 'carrefour_contact'
}

item {
  id: 9
  name: 'carrefour_express'
}

item {
  id: 10
  name: 'carrefour_city'
}

item {
  id: 11
  name: 'securitest'
}

item {
  id: 12
  name: 'autosecurite'
}

item {
  id: 13
  name: 'no_logo'
}
