item {
  id: 1
  name: 'carrefour_market'
}

item {
  id: 2
  name: 'intermarche'
}

item {
  id: 3
  name: 'aldi'
}

item {
  id: 4
  name: 'fedex'
}

item {
  id: 5
  name: 'esso'
}

item {
  id: 6
  name: 'google'
}

item {
  id: 7
  name: 'no-logo'
}
